### ISSUE TITLE
auto refresh ?

### ISSUE THREAD

**Issue by chqzeng** [KeshiaRose/Basic-CSV-WDC#13]
great work to setup this WDC for csv, thx! 
I am wondering if the csv file will be auto refreshed into Tableau, and if yes, at what frequency? could we somewhere to set this frequency in Tableau or your script?
I am very new to Tableau, and currently use the Tableau Desktop and connect to a url of csv file in our shared FTP. and this csv file will updated every few hours, and I will need these changes be updated pretty frequently to Tableau.
Chui

**Comment by KeshiaRose** [comment]
Hi @chqzeng, thanks for the feedback! 🙂 The WDC data will not be refreshed automatically but you have a couple of options for refreshes:

**Manual Refresh in Tableau Desktop**

You can always select the **data source** > **Extract** > **Refresh Extract** to refresh the data at any time from within Tableau Desktop.

**Automate Refresh in Tableau Server**

If you want to use this WDC on your Tableau Server you will first need to [add it to your safelist](https://help.tableau.com/current/server/en-us/datasource_wdc.htm) with the following commands:

```
tsm data-access web-data-connectors add --name "CSV WDC" --url https://basic-csv-wdc.herokuapp.com:443
tsm pending-changes apply
```

Applying this change will cause your server to restart. Once completed you can simply publish the data source to Tableau Server and set it up to [refresh on a schedule](https://help.tableau.com/current/server/en-us/qs_refresh_extracts.htm) there.

**Automate Refresh in Tableau Cloud/Online with Bridge**

If you want to use this WDC on Tableau Online you will need to set it up using [Tableau Bridge](https://help.tableau.com/current/online/en-us/qs_refresh_local_data.htm)

Hope this helps!

**Comment by chqzeng** [comment]
thank you for the quick reply! 
with Tableau Bridge, do I need a local machine always running to keep refreshing the data from WDC? 
We have a Tableau Creator subscription that I assume have Tableau Cloud, and currently we use Tableau Desktop to push the data to Tableau Public Vizzes.  It updates daily, without local machine, using Google Drive datasource.  I want to replace this google drive datasource with your WDC approach, while still able to auto refreshing without requiring a local machine running dedicated for that purpose. 
I am very new to Tableau, so some comment would be very appreciated.
Chui

**Comment by KeshiaRose** [comment]
@chqzeng Yes, unfortunately for Tableau Bridge you need to have a machine (local or not) always running to refresh a WDC automatically. Honestly, I think using Google Sheets as the data source with an [app script](https://developers.google.com/apps-script) that automatically fetches data and populates the sheet is a good idea. I've done this for a couple of people through [Fiverr](https://www.fiverr.com/keshiarose/create-a-custom-tableau-web-data-connector) and this always ends up being the preferred method because of how easy it is to keep fresh. I have an old [blog post](https://sliceofkeesh.com/post/automatically-update-google-sheet-hosted-csv) that shows one way you can do this if you're interested in trying it out with your CSV. Other than that, I haven't tried out the new WDC 3.0 so perhaps there are some new benefits there?
