### ISSUE TITLE
Trouble connecting to a CSV in GitHub

### ISSUE THREAD

**Issue by Miguelangelortizh** [KeshiaRose/Basic-CSV-WDC#6]
Keshia, thanks for helping us a lot. But I have a situation when trying to get the data from this repository on GitHub (https://github.com/owid/covid-19-data/tree/master/public/data) to create a dashboard on Tableau. I don't know what is going on because when I get the data there is not observation (no rows) in the dataset so I think there is a problem when reading the CSV file.

**Comment by KeshiaRose** [comment]
Hi @Miguelangelortizh, thanks for bringing this to my attention! It looks like Tableau was having trouble appending that many rows all at once. I've now set it so that rows are appended in 10k row chunks and the CSV from that page works for me now. Test it out and let me know if it works for you, if not feel free to re-open this ticket!
-Keshia
